### ISSUE TITLE
Xbacklight causes crashes

### ISSUE THREAD

**Issue by shinglyu** [Agneli/linux-remote-control#51]
- Steps
  1. Start the server
- Expected 
  The server quietly wating for requests
- Actual 

```
% node /opt/lrc-server/lrc.js                                                                                8 ↵ ✖ ✹ ✭
Listening on port 3000

/opt/lrc-server/lrc.js:104
                backlight = backlight[1].replace(/^\s+|\s+$/g, "");
                                         ^
TypeError: Cannot call method 'replace' of undefined
    at /opt/lrc-server/lrc.js:104:42
    at ChildProcess.exithandler (child_process.js:635:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Socket.<anonymous> (child_process.js:956:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

Maybe we can add a shortcut to ignore the backlight part. I don't really need to control my backlight after all.

**Comment by Agneli** [comment]
Hi @shinglyu.
Sorry for my delay in responding.

Can you try reinstall the following softwares: xdotool, xbacklight and nodejs
Maybe it can solve your problem.

**Comment by shinglyu** [comment]
I'll try it soon, I'm quite occupied right now. Thanks.

**Comment by iGormilhit** [comment]
Hi @Agneli @shinglyu 

I have the same problem, with the same error message. I've been trying to `apt-get install --reinstall xdotool xbacklight nodejs`, but I'm still having the crash.
